# TEST CODE
### We will be practicing git here. Also trying to fix code in a shared environment. 

In [2]:
import astropy
import matplotlib

In [3]:
import csv
import numpy as np

### Thanks, Emma! I have the files to test now. 

In [4]:
cz=[]
with open('Barton_Table_New_float.csv') as csv_file:
    cz_temp = np.genfromtxt(csv_file, dtype=float, delimiter=',', filling_values=9999, usecols=[1])
    #print(cz_temp)
    cz = np.append(cz, cz_temp)

print(cz)


[ 5590.  5770.  5445.  5422.  5222.  5645.  5070.  5148.  4466.  4572.
  5809.  5485.  4338.  4381.  4261.  4369.  4793.  5096.  5270. 12443.
 12741. 11755. 11561.  5605.  5323.  5603. 14329. 14802.  2596.  2422.
  6188.  6077.  6200.  5638.  4557.  4661.  4089.  3995.  4039.  5763.
  5704.  3355.  3477.  5267.  5338.  7917.  7882.  4366.  4339.  3162.
  3086.  2330.  2479.  2984.  3033. 10778. 11394. 11040. 11260.  2488.
  2618.  6056.  5100.  6858.  8318.  8438.  8490.  8591.  3065.  3005.
  3016.  5988.  5971.  7533.  7382.  6886.  7532.  7243.  7118.  7538.
  7814.  3653.  3771.  6169.  6227.  3015.  6896.  2676.  2602.  3267.
  3208.  3164.  3259.  3079.  4820.  3325.  4696.  6310.  6230.  3998.
  3816.  3790.  4031.  4013.  4944.  4806.  4761.  6623.  6608.  6158.
  5998.  6329.  6367.  6492.  6979.  2360.  2490.  6974.  7384.  2282.
  2317.  2830.  2802. 11599. 11788.  2874.  2838.  4661.  4728.  2667.
  2656.  5601.  5715.  6704.  6541.  6759.  4838.  4856.  5787.  5533.
  6230

### Let's play with where commands... useful for flagging and excluding from analysis and plots. 

#### E.g. We want to only include sources where the cz values are less than 6000. 

In [14]:
cz_good = cz[np.where(cz < 6000.)]
cz_good

array([5590., 5770., 5445., 5422., 5222., 5645., 5070., 5148., 4466.,
       4572., 5809., 5485., 4338., 4381., 4261., 4369., 4793., 5096.,
       5270., 5605., 5323., 5603., 2596., 2422., 5638., 4557., 4661.,
       4089., 3995., 4039., 5763., 5704., 3355., 3477., 5267., 5338.,
       4366., 4339., 3162., 3086., 2330., 2479., 2984., 3033., 2488.,
       2618., 5100., 3065., 3005., 3016., 5988., 5971., 3653., 3771.,
       3015., 2676., 2602., 3267., 3208., 3164., 3259., 3079., 4820.,
       3325., 4696., 3998., 3816., 3790., 4031., 4013., 4944., 4806.,
       4761., 5998., 2360., 2490., 2282., 2317., 2830., 2802., 2874.,
       2838., 4661., 4728., 2667., 2656., 5601., 5715., 4838., 4856.,
       5787., 5533., 5780., 4944., 4798., 2926., 3064., 4608., 4982.,
       4095., 4208., 5089., 5286., 5441., 4979., 4846., 5965., 2888.,
       2840., 3069., 3052., 3108., 5603., 4349., 4669., 5621., 5154.,
       5085., 4550., 4809.])

Note: here the [] include the indices that satistfy the where command. So the np.where() function returns the indices for cz that are < 6000. If you use the np.where(condition, x, y) usage then the x and y will REPLACE the array with values x where the condition is TRUE and y where the condition is false. I show this below for fun. But, the above is what you want for simply filtering what you show/plot/etc. 

In [12]:
# This puts 0 for cz < 6000 and cz for cz  not < 6000. 
np.where(cz < 6000, 0, cz)

array([    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0., 12443., 12741., 11755., 11561.,     0.,
           0.,     0., 14329., 14802.,     0.,     0.,  6188.,  6077.,
        6200.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,  7917.,  7882.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0., 10778.,
       11394., 11040., 11260.,     0.,     0.,  6056.,     0.,  6858.,
        8318.,  8438.,  8490.,  8591.,     0.,     0.,     0.,     0.,
           0.,  7533.,  7382.,  6886.,  7532.,  7243.,  7118.,  7538.,
        7814.,     0.,     0.,  6169.,  6227.,     0.,  6896.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,  6310.,  6230.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,  6623.,  6608.,  6158.,     0.,  6329.,
      

In [13]:
# This puts cz for cz < 6000 and -1000 for cz not < 6000. 
np.where(cz < 6000, cz, -1000.)

array([ 5590.,  5770.,  5445.,  5422.,  5222.,  5645.,  5070.,  5148.,
        4466.,  4572.,  5809.,  5485.,  4338.,  4381.,  4261.,  4369.,
        4793.,  5096.,  5270., -1000., -1000., -1000., -1000.,  5605.,
        5323.,  5603., -1000., -1000.,  2596.,  2422., -1000., -1000.,
       -1000.,  5638.,  4557.,  4661.,  4089.,  3995.,  4039.,  5763.,
        5704.,  3355.,  3477.,  5267.,  5338., -1000., -1000.,  4366.,
        4339.,  3162.,  3086.,  2330.,  2479.,  2984.,  3033., -1000.,
       -1000., -1000., -1000.,  2488.,  2618., -1000.,  5100., -1000.,
       -1000., -1000., -1000., -1000.,  3065.,  3005.,  3016.,  5988.,
        5971., -1000., -1000., -1000., -1000., -1000., -1000., -1000.,
       -1000.,  3653.,  3771., -1000., -1000.,  3015., -1000.,  2676.,
        2602.,  3267.,  3208.,  3164.,  3259.,  3079.,  4820.,  3325.,
        4696., -1000., -1000.,  3998.,  3816.,  3790.,  4031.,  4013.,
        4944.,  4806.,  4761., -1000., -1000., -1000.,  5998., -1000.,
      